drop table HASWORKED cascade constraints;
drop table ACCOUNT cascade constraints;
drop sequence add_account_id;
drop table BusCard cascade constraints;
drop table STOP cascade constraints;
drop table VISITED cascade constraints;
drop table POINTOFINTEREST cascade constraints;
drop table SCHOOL cascade constraints;
drop table HASPLAYGROUND cascade constraints;
drop table PARK cascade constraints;
drop table RESTAURANT cascade constraints;
drop table ATTRACTION cascade constraints;
drop table POICLOSESTTO cascade constraints;
drop table GARAGE cascade constraints;
drop table TRANSITLINE cascade constraints;
drop table LINESTOPS cascade constraints;
drop table VEHICLE cascade constraints;
drop table VEHICLETYPE cascade constraints;
drop table OPERATOR cascade constraints;
drop table VEHICLELICENSE cascade constraints;
purge recyclebin;